### ISSUE TITLE
Client-side `NullPointerException` ticking `TileEntityFan`

### ISSUE THREAD

**Issue by abel1502** [JameH2/Hbm-s-Nuclear-Tech-GIT#150]
When playing on a remote server with a manual latest build of the mod, I encountered a client-side crash when I teleported to an area in the overworld containing fans. The full crashlog is attached below. I belive the issue is that `ChunkAtmosphereHandler` only populates the blobs dict on the server, but it is apparently referenced by the client as well.

https://github.com/JameH2/Hbm-s-Nuclear-Tech-GIT/blob/24c11e12df33b85f355cf9845b62720e769c8b97/src/main/java/com/hbm/handler/atmosphere/ChunkAtmosphereHandler.java#L273-L276

https://github.com/JameH2/Hbm-s-Nuclear-Tech-GIT/blob/24c11e12df33b85f355cf9845b62720e769c8b97/src/main/java/com/hbm/blocks/machine/MachineFan.java#L77-L82

Crashlog:

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 29.09.24 23:30
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:58)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:49)
	at com.hbm.blocks.machine.MachineFan$TileEntityFan.func_145845_h(MachineFan.java:82)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:58)
	at com.hbm.handler.atmosphere.ChunkAtmosphereHandler.getAtmosphere(ChunkAtmosphereHandler.java:49)
	at com.hbm.blocks.machine.MachineFan$TileEntityFan.func_145845_h(MachineFan.java:82)

-- Block entity being ticked --
Details:
	Name: tileentity_fan // com.hbm.blocks.machine.MachineFan.TileEntityFan
	Block type: ID #1094 (tile.fan // com.hbm.blocks.machine.MachineFan)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-612,207,-109), Chunk: (at 12,12,3 in -39,-7; contains blocks -624,0,-112 to -609,255,-97), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #1094 (tile.fan // com.hbm.blocks.machine.MachineFan)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['abel1502'/128, l='MpServer', x=-603,50, y=211,12, z=-102,50]]
	Chunk stats: MultiplayerChunkCache: 164, 164
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,220), Chunk: (at 0,4,12 in -14,13; contains blocks -224,0,208 to -209,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13677248 game time, 16250854 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntitySquid['Squid'/71681, l='MpServer', x=-643,50, y=62,00, z=-66,50], EntitySquid['Squid'/71680, l='MpServer', x=-644,50, y=62,00, z=-67,50], EntitySquid['Squid'/71683, l='MpServer', x=-643,50, y=62,00, z=-67,50], EntitySquid['Squid'/71682, l='MpServer', x=-645,50, y=62,00, z=-66,50], EntitySquid['Squid'/71685, l='MpServer', x=-643,50, y=62,00, z=-63,50], EntitySquid['Squid'/71684, l='MpServer', x=-640,50, y=62,00, z=-63,50], EntityClientPlayerMP['abel1502'/128, l='MpServer', x=-603,50, y=211,12, z=-102,50], EntitySquid['Squid'/71699, l='MpServer', x=-664,50, y=56,00, z=-118,50], EntitySquid['Squid'/71698, l='MpServer', x=-666,50, y=56,00, z=-117,50], EntitySquid['Squid'/71701, l='MpServer', x=-666,50, y=56,00, z=-116,50], EntitySquid['Squid'/71700, l='MpServer', x=-663,50, y=56,00, z=-119,50], EntitySquid['Squid'/71703, l='MpServer', x=-664,50, y=56,00, z=-129,50], EntitySquid['Squid'/71702, l='MpServer', x=-661,50, y=56,00, z=-125,50], EntitySquid['Squid'/71705, l='MpServer', x=-662,50, y=56,00, z=-129,50], EntitySquid['Squid'/71704, l='MpServer', x=-661,50, y=56,00, z=-129,50], EntitySquid['Squid'/71744, l='MpServer', x=-638,50, y=50,00, z=-166,50], EntitySquid['Squid'/71746, l='MpServer', x=-636,50, y=50,00, z=-164,50], EntitySquid['Squid'/71749, l='MpServer', x=-563,50, y=52,00, z=-65,50], EntitySquid['Squid'/71748, l='MpServer', x=-561,50, y=52,00, z=-65,50], EntitySquid['Squid'/71750, l='MpServer', x=-563,50, y=52,00, z=-70,50], EntitySquid['Squid'/71753, l='MpServer', x=-566,50, y=52,00, z=-64,50], EntitySquid['Squid'/71754, l='MpServer', x=-562,50, y=52,00, z=-69,50], EntitySquid['Squid'/71815, l='MpServer', x=-648,50, y=52,00, z=-143,50], EntitySquid['Squid'/71817, l='MpServer', x=-646,50, y=52,00, z=-140,50], EntitySquid['Squid'/71816, l='MpServer', x=-649,50, y=52,00, z=-140,50], EntitySquid['Squid'/71819, l='MpServer', x=-644,50, y=52,00, z=-146,50], EntitySquid['Squid'/71818, l='MpServer', x=-644,50, y=52,00, z=-139,50], EntitySquid['Squid'/71821, l='MpServer', x=-647,50, y=52,00, z=-144,50], EntitySquid['Squid'/71820, l='MpServer', x=-645,50, y=52,00, z=-145,50], EntitySquid['Squid'/71823, l='MpServer', x=-644,50, y=52,00, z=-142,50], EntitySquid['Squid'/71822, l='MpServer', x=-648,50, y=52,00, z=-142,50], EntitySquid['Squid'/71825, l='MpServer', x=-645,50, y=52,00, z=-141,50], EntitySquid['Squid'/71824, l='MpServer', x=-642,50, y=52,00, z=-141,50], EntitySquid['Squid'/71826, l='MpServer', x=-646,50, y=52,00, z=-136,50], EntitySquid['Squid'/71851, l='MpServer', x=-651,50, y=57,00, z=-64,50], EntitySquid['Squid'/71853, l='MpServer', x=-656,50, y=57,00, z=-62,50], EntitySquid['Squid'/71852, l='MpServer', x=-655,50, y=57,00, z=-60,50], EntitySquid['Squid'/71855, l='MpServer', x=-654,50, y=57,00, z=-64,50], EntitySquid['Squid'/71857, l='MpServer', x=-656,50, y=57,00, z=-65,50], EntitySquid['Squid'/71856, l='MpServer', x=-656,50, y=57,00, z=-64,50], EntitySquid['Squid'/71859, l='MpServer', x=-650,50, y=57,00, z=-59,50], EntitySquid['Squid'/71858, l='MpServer', x=-658,50, y=57,00, z=-63,50], EntitySquid['Squid'/71861, l='MpServer', x=-652,50, y=57,00, z=-57,50], EntitySquid['Squid'/71860, l='MpServer', x=-655,50, y=57,00, z=-58,50], EntitySquid['Squid'/71862, l='MpServer', x=-652,50, y=57,00, z=-52,50], EntityZombie['Zombie'/166600, l='MpServer', x=46,51, y=-0,09, z=-8,52], EntitySquid['Squid'/71443, l='MpServer', x=-622,50, y=56,00, z=-134,50], EntitySquid['Squid'/71445, l='MpServer', x=-625,50, y=56,00, z=-134,50], EntitySquid['Squid'/71444, l='MpServer', x=-626,50, y=56,00, z=-136,50], EntitySquid['Squid'/71447, l='MpServer', x=-617,50, y=56,00, z=-138,50], EntitySquid['Squid'/71446, l='MpServer', x=-627,50, y=56,00, z=-136,50], EntitySquid['Squid'/71449, l='MpServer', x=-612,50, y=56,00, z=-138,50], EntitySquid['Squid'/71448, l='MpServer', x=-613,50, y=56,00, z=-134,50], EntitySquid['Squid'/71451, l='MpServer', x=-621,50, y=56,00, z=-140,50], EntitySquid['Squid'/71450, l='MpServer', x=-610,50, y=56,00, z=-141,50], EntitySquid['Squid'/71453, l='MpServer', x=-627,50, y=56,00, z=-145,50], EntitySquid['Squid'/71452, l='MpServer', x=-625,50, y=56,00, z=-145,50], EntitySquid['Squid'/71454, l='MpServer', x=-624,50, y=56,00, z=-145,50], EntitySquid['Squid'/71507, l='MpServer', x=-665,50, y=59,00, z=-147,50], EntitySquid['Squid'/71506, l='MpServer', x=-661,50, y=59,00, z=-148,50], EntitySquid['Squid'/71509, l='MpServer', x=-666,50, y=59,00, z=-152,50], EntitySquid['Squid'/71508, l='MpServer', x=-665,50, y=59,00, z=-149,50], EntitySquid['Squid'/71511, l='MpServer', x=-667,50, y=59,00, z=-150,50], EntitySquid['Squid'/71513, l='MpServer', x=-666,50, y=59,00, z=-145,50], EntitySquid['Squid'/72071, l='MpServer', x=-575,50, y=54,00, z=-133,50], EntitySquid['Squid'/72070, l='MpServer', x=-574,50, y=54,00, z=-132,50], EntitySquid['Squid'/72073, l='MpServer', x=-574,50, y=54,00, z=-134,50], EntitySquid['Squid'/72072, l='MpServer', x=-574,50, y=54,00, z=-130,50], EntitySquid['Squid'/72075, l='MpServer', x=-576,50, y=54,00, z=-127,50], EntitySquid['Squid'/72074, l='MpServer', x=-573,50, y=54,00, z=-131,50], EntitySquid['Squid'/72077, l='MpServer', x=-573,50, y=54,00, z=-128,50], EntitySquid['Squid'/72076, l='MpServer', x=-577,50, y=54,00, z=-129,50], EntitySquid['Squid'/72079, l='MpServer', x=-571,50, y=54,00, z=-130,50], EntitySquid['Squid'/72078, l='MpServer', x=-571,50, y=54,00, z=-131,50], EntitySquid['Squid'/72081, l='MpServer', x=-572,50, y=54,00, z=-125,50], EntitySquid['Squid'/72116, l='MpServer', x=-561,50, y=57,00, z=-130,50], EntitySquid['Squid'/72135, l='MpServer', x=-579,50, y=49,00, z=-66,50], EntitySquid['Squid'/72134, l='MpServer', x=-565,50, y=49,00, z=-64,50], EntitySquid['Squid'/72137, l='MpServer', x=-580,50, y=49,00, z=-64,50], EntitySquid['Squid'/71675, l='MpServer', x=-648,50, y=62,00, z=-73,50], EntitySquid['Squid'/71674, l='MpServer', x=-647,50, y=62,00, z=-72,50], EntitySquid['Squid'/71676, l='MpServer', x=-646,50, y=62,00, z=-75,50], EntitySquid['Squid'/71679, l='MpServer', x=-641,50, y=62,00, z=-69,50], EntitySquid['Squid'/71678, l='MpServer', x=-642,50, y=62,00, z=-70,50]]
	Retry entities: 18 total; [EntityZombie['Zombie'/69099, l='MpServer', x=-863,50, y=37,00, z=51,50], EntityCreeper['Creeper'/69226, l='MpServer', x=-833,50, y=18,00, z=-38,50], EntityBat['Bat'/67053, l='MpServer', x=-824,56, y=29,51, z=-52,75], EntityCreeper['Creeper'/66542, l='MpServer', x=-788,50, y=14,00, z=-103,50], EntitySpider['Spider'/68593, l='MpServer', x=-855,03, y=20,00, z=-96,50], EntityCreeper['Creeper'/68592, l='MpServer', x=-857,88, y=15,00, z=-103,25], EntityPig['Pig'/54135, l='MpServer', x=-823,88, y=79,00, z=27,78], EntityPig['Pig'/54136, l='MpServer', x=-824,09, y=79,00, z=22,84], EntityCreeper['Creeper'/68857, l='MpServer', x=-802,50, y=13,00, z=-86,50], EntityMinecartChest['entity.MinecartChest.name'/54137, l='MpServer', x=-858,50, y=40,50, z=-13,50], EntitySkeleton['Skeleton'/68856, l='MpServer', x=-800,50, y=13,00, z=-86,50], EntityPig['Pig'/54138, l='MpServer', x=-848,06, y=77,00, z=-9,28], EntityPig['Pig'/54139, l='MpServer', x=-859,88, y=70,00, z=-8,25], EntityPig['Pig'/54140, l='MpServer', x=-851,34, y=70,00, z=-1,53], EntityBat['Bat'/68221, l='MpServer', x=-821,72, y=30,51, z=-53,13], EntityPig['Pig'/54141, l='MpServer', x=-863,06, y=74,00, z=-15,19], EntityDuck['Duck'/54142, l='MpServer', x=-858,72, y=67,00, z=-3,47], EntityPig['Pig'/54143, l='MpServer', x=-813,34, y=79,00, z=32,47]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1304158968 bytes (1243 MB) / 2602041344 bytes (2481 MB) up to 15181807616 bytes (14478 MB)
	JVM Flags: 2 total; -Xmx16288m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Angelica 1.0.0-beta6 56 mods loaded, 56 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	CodeChickenCore{1.3.7} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	fullscreenwhileinactive{1.0.0} [FullscreenWhileInactive] (minecraft.jar) 
	UCHIJA	NotEnoughItems{2.6.39-GTNH} [NotEnoughItems] (NotEnoughItems-2.6.39-GTNH.jar) 
	UCHIJA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJA	unimixins{0.1.17} [UniMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	unimixins-compat{0.1.17} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	mixinextras{0.1.17} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJA	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-beta6.jar) 
	UCHIJA	notfine{1.0.0-beta6} [NotFine] (angelica-1.0.0-beta6.jar) 
	UCHIJA	embeddium{1.0.0-beta6} [Embeddium] (angelica-1.0.0-beta6.jar) 
	UCHIJA	gtnhlib{0.5.12} [GTNH Lib] (gtnhlib-0.5.12.jar) 
	UCHIJA	angelica{1.0.0-beta6} [Angelica] (angelica-1.0.0-beta6.jar) 
	UCHIJA	AppleCore{3.3.2} [AppleCore] (AppleCore-3.3.2.jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UCHIJA	AromaBackup{0.1.0.0} [AromaBackup] (AromaBackup-1.7.10-0.1.0.0.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.1.0.0.jar) 
	UCHIJA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJA	betterboat{1.1.0} [Better Boat] (BetterBoat-1.7.10-1.1.0.jar) 
	UCHIJA	catwalks{2.0.4} [Catwalks Mod] (catwalks-2.0.4.jar) 
	UCHIJA	catwalkmod{x.x.x} [Legacy Catwalk Compat] (catwalks-2.0.4.jar) 
	UCHIJA	clayconversion{1.0} [Clay Conversion] (Clay Conversion1.7.10-1.0.jar) 
	UCHIJA	controlling{1.7.10-1.0.0.8} [Controlling] (Controlling-1.7.10-1.0.0.8.jar) 
	UCHIJA	craftingtweaks{1.0.88} [Crafting Tweaks] (craftingtweaks-mc1.7.10-1.0.88.jar) 
	UCHIJA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJA	hbm{1.0.27 BETA (5091)} [Hbm's Nuclear Tech] (HBM-NTM-1.0.27_X5103-A01_H261.jar) 
	UCHIJA	HelpFixer{1.0.7} [HelpFixer] (HelpFixer-1.0.7.jar) 
	UCHIJA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
	UCHIJA	mending{1.0} [Mending for 1.7.10] (Mending for 1.7.10-1.1.jar) 
	UCHIJA	Morpheus{1.7.10-1.6.21} [Morpheus] (Morpheus-1.7.10-1.6.21.jar) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-1.7.10-0.3.2.jar) 
	UCHIJA	notes{1.1.1} [Notes] (Notes-1.7.10-1.1.1.jar) 
	UCHIJA	clayspawn{1.7.10b} [Pam's Clayspawn] (Pam's Clay Spawn 1.7.10b.jar) 
	UCHIJA	sleepingbag{0.1.1} [Sleeping Bag] (SleepingBag-1.7.10-0.1.1.jar) 
	UCHIJA	VeinMiner{0.36.0_1.7.10-28a7f13} [Vein Miner] (WA-VeinMiner-1.7.10-0.36.0.496.jar) 
	UCHIJA	VeinMinerModSupport{0.36.0_1.7.10-28a7f13} [Mod Support] (WA-VeinMiner-1.7.10-0.36.0.496.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHIJA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJA	XaeroMinimap{21.10.42} [Xaero's Minimap] (Xaeros_Minimap_21.10.42_Forge_1.7.10.jar) 
	UCHIJA	XaeroWorldMap{1.14.1.32} [Xaero's World Map] (XaerosWorldMap_1.14.1.32_Forge_1.7.10.jar) 
	UCHIJA	zume{1.1.2} [Zume] (zume-1.1.2.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7642' Renderer: 'Intel(R) UHD Graphics'
	NTM Modified recipes:: 
	Mixins in Stacktrace: 
		net.minecraft.client.Minecraft:
			mixins.angelica.early.json:sodium.MixinMinecraft from mod angelica
			mixins.angelica.early.json:angelica.MixinMinecraft from mod angelica
		net.minecraft.world.World:
			mixins.angelica.early.json:angelica.lighting.MixinWorld_FixLightUpdateLag from mod angelica
			mixins.angelica.early.json:angelica.dynamiclights.MixinWorld from mod angelica
	Launched Version: forge-10.13.4.1614
	LWJGL: 2.9.1
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.7642, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by MellowArpeggiation** [comment]
Thanks for the report, let me know if you have any more issues with the fan block
