### ISSUE TITLE
random crashing

### ISSUE THREAD

**Issue by destroyer410** [JameH2/Hbm-s-Nuclear-Tech-GIT#172]
I was trying to Explore laythe but i have alot of random crashing, this problem isnt just laythe either it most if not all the planets.

 java.lang.ArrayIndexOutOfBoundsException: 4
	at com.hbm.dim.BiomeGenBaseCelestial.func_76747_a(BiomeGenBaseCelestial.java:24)
	at com.hbm.dim.ChunkProviderCelestial.func_73155_a(ChunkProviderCelestial.java:396)
	at com.hbm.dim.laythe.ChunkProviderLaythe.func_73155_a(ChunkProviderLaythe.java:66)
	at net.minecraft.world.gen.ChunkProviderServer.func_73155_a(ChunkProviderServer.java:379)
	at net.minecraft.world.WorldServer.func_73057_a(WorldServer.java:201)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by destroyer410** [comment]
Managed to find out what the issue was

**Comment by MellowArpeggiation** [comment]
What was the issue?
