### ISSUE TITLE
Crash with openblock Mod(?)

### ISSUE THREAD

**Issue by iamsoNewBee** [JameH2/Hbm-s-Nuclear-Tech-GIT#188]
[crash-2024-12-25_18.52.54-server.txt](https://github.com/user-attachments/files/18245570/crash-2024-12-25_18.52.54-server.txt)
When i see a missile.

**Comment by Fivebuss** [comment]
From a quick glance at your log it appears to be caused by an HBM turret, specifically "howard"

>	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.spawnCasing(TileEntityTurretBaseNT.java:893)
	at com.hbm.tileentity.turret.TileEntityTurretHowardDamaged.updateFiringTick(TileEntityTurretHowardDamaged.java:79)
	at com.hbm.tileentity.turret.TileEntityTurretBaseNT.func_145845_h(TileEntityTurretBaseNT.java:226)
	at com.hbm.tileentity.turret.TileEntityTurretHoward.func_145845_h(TileEntityTurretHoward.java:127)

You should be able to temporarily fix it by removing the block
> World: (-235,87,951), Chunk: (at 5,5,7 in -15,59; contains blocks -240,0,944 to -225,255,959), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)

If this still happens AND in stock HBM, make a report there because it might be unrelated to NTM: Space's changes

**Comment by MellowArpeggiation** [comment]
Can you make sure you're on the latest version? This looks similar to an issue that was already resolved 2 months ago.

**Comment by MellowArpeggiation** [comment]
Oh my bad, checked the issue date, this has definitely been resolved since then, closing as fixed.
